### ISSUE TITLE
Driver Standby/Reset Pins

### ISSUE THREAD

**Issue by NathanDus** [oresat/oresat-acs-board#1]
The STBY/RESET pins on both the STSPIN230 and STSIN250 need to be reverted back to rev1.1

**Comment by E-Ruhl** [comment]
We also need to look into weather it would be better to alternate the enable pin off the MCU or if we get lower power usage by dissabling the Standby pin instead of the enable pin.

**Comment by E-Ruhl** [comment]
Stepping up to the L4 allowed us to put both pins on GPIO
