### ISSUE TITLE
Delete 'Board Schematic PDFs' folder

### ISSUE THREAD

**Issue by NathanDus** [oresat/oresat-acs-board#2]
Hi Eric, I don't know how to cleanly remove things from Git. It doesn't like it when I try. Can you delete the folder 'Board Schematic PDFs'? Its not needed anymore. We have things in the 'Board Schematic PDFs and Images' folder.

**Comment by heliochronix** [comment]
@NathanDus,
To remove something from Git, use `git rm`. It acts pretty much like regular `rm` but also stages the changes inside git. For example, in the oresat-acs-board directory you would do `git rm -r Board\ Schematic\ PDFs`. Hope that helps!

**Comment by heliochronix** [comment]
Also, then you would `git commit` the changes. Note that empty directories are automatically removed from git repositories if there's nothing inside.
